spring:
  application:
    name: springboot-app
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/lawaier
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: admin
      password: 1234
jwt:
  secret:
    key: bXktdmVyeS1zZWN1cmUtYW5kLXJhbmRvbS1zZWNyZXQta2V5LTEyMzQ1Ng==