spring:
  application:
    name: springboot-app
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  secret:
    key: bXktdmVyeS1zZWN1cmUtYW5kLXJhbmRvbS1zZWNyZXQta2V5LTEyMzQ1Ng==

chatbot:
  base:
    url: http://chatbot-app:8000